GET http://localhost:3001/api/persons
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/631100fc89d3c609f5ef7f87
###
DELETE http://localhost:3001/api/persons/6311c84de59ed0abd89b8479
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{   
    "name": "Te",
    "number": "08512712571" 
}

###
PUT http://localhost:3001/api/persons/631100fc89d3c609f5ef7f87
Content-Type: application/json

{
    "name": "Debora"
    "number": "0888-6969"
}